### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by Havvy** [pirogoeth/ashiema#1]
This code is unlicensed, which means that we cannot actually use it legally. While I doubt you are going to sue anybody for using it, the license makes it clear you won't.

**Comment by ccrama** [comment]
A bit off topic, but there is also lack of documentation.

**Comment by pirogoeth** [comment]
Yeah, I never got around to documentation.  I can start working some stuff up.

**Comment by pirogoeth** [comment]
Alright, took care of the lack of license, I'll start writing some documentation.

**Comment by ccrama** [comment]
Nice, thanks

**Comment by pirogoeth** [comment]
No problem!
