### ISSUE TITLE
Exits if someone speaks

### ISSUE THREAD

**Issue by ccrama** [pirogoeth/ashiema#3]
Sorry to be such a pain x.x . It gives me this error on startup

{ashiema}[ERROR/2013-03-10 07:58:41,816]: You must install py-megahal to use this plugin.
{ashiema}[INFO/2013-03-10 07:58:41,834]: an error has occurred in SystemFunctions (1.0):
{ashiema}[ERROR/2013-03-10 07:58:41,839]: Traceback (most recent call last):
{ashiema}[ERROR/2013-03-10 07:58:41,843]:   File "/server/Bot/core/PluginLoader.py", line 99, in load
{ashiema}[ERROR/2013-03-10 07:58:41,847]:     plugin : data['main'](self.connection, self.eventhandler)
{ashiema}[ERROR/2013-03-10 07:58:41,851]:   File "/server/Bot/plugins/System.py", line 41, in **init**
{ashiema}[ERROR/2013-03-10 07:58:41,855]:     self.system_event = SystemEvent(eventhandler)
{ashiema}[ERROR/2013-03-10 07:58:41,858]:   File "/server/Bot/plugins/System.py", line 17, in **init**
{ashiema}[ERROR/2013-03-10 07:58:41,862]:     Event.Event.**init**(self, eventhandler)
{ashiema}[ERROR/2013-03-10 07:58:41,866]: TypeError: **init**() takes exactly 3 arguments (2 given)
{ashiema}[ERROR/2013-03-10 07:58:41,869]: 
{ashiema}[INFO/2013-03-10 07:58:41,873]: an error has occurred in ArtificialIntelligence (1.0):
{ashiema}[ERROR/2013-03-10 07:58:41,877]: Traceback (most recent call last):
{ashiema}[ERROR/2013-03-10 07:58:41,880]:   File "/server/Bot/core/PluginLoader.py", line 99, in load
{ashiema}[ERROR/2013-03-10 07:58:41,883]:     plugin : data['main'](self.connection, self.eventhandler)
{ashiema}[ERROR/2013-03-10 07:58:41,887]:   File "/server/Bot/plugins/ArtificialIntelligence.py", line 31, in **init**
{ashiema}[ERROR/2013-03-10 07:58:41,890]:     self.brain = megahal.MegaHAL(brainfile = self.get_path() + "/brain")
{ashiema}[ERROR/2013-03-10 07:58:41,893]: NameError: global name 'megahal' is not defined
{ashiema}[ERROR/2013-03-10 07:58:41,896]: 
{ashiema}[INFO/2013-03-10 07:58:41,900]: all plugins have been loaded.
{ashiema}[DEBUG/2013-03-10 07:58:41,903]: LimitBot MODE LimitBot +iwx
{ashiema}[DEBUG/2013-03-10 07:58:41,912]: NickServ!services@mibbit.net NOTICE LimitBot Your nick isn't registered.
{ashiema}[DEBUG/2013-03-10 07:58:41,915]: irc.va.us.mibbit.net 402 LimitBot ashiema :No such server
{ashiema}[DEBUG/2013-03-10 07:58:41,968]: irc.va.us.mibbit.net 332 LimitBot #limitsmp :
{ashiema}[DEBUG/2013-03-10 07:58:41,974]: irc.va.us.mibbit.net 333 LimitBot #limitsmp ChanServ 1362920136
{ashiema}[DEBUG/2013-03-10 07:58:41,980]: irc.va.us.mibbit.net 353 LimitBot = #limitsmp :LimitBot ~ccrama 
{ashiema}[DEBUG/2013-03-10 07:58:41,983]: irc.va.us.mibbit.net 366 LimitBot #limitsmp :End of /NAMES list.
{ashiema}[DEBUG/2013-03-10 07:58:45,093]: ccrama!Mibbit@mib-1F2D8DEB.lightspeed.ftwotx.sbcglobal.net PRIVMSG #limitsmp hi

and it DOES connect, but if someone talks, it crashes.

**Comment by ccrama** [comment]
Also, on startup it says you must have py-megahal to use this plugin, and invalid file format for users.db

**Comment by pirogoeth** [comment]
I believe I've fixed the problems with the "exiting on speech" and the megahal stuff, but the "invalid file format" is due to lack of a database..open up your tools/ directory and run makeuser.py, then try to start the bot.

**Comment by ccrama** [comment]
what is the preferred permission? It says choose 1 2 or 3

**Comment by ccrama** [comment]
and the newest version still says I need megahal

**Comment by pirogoeth** [comment]
Permissions are from 0 to 2, 0 is basically the lowest, and 2 is basically "bot administrator".  So your choice :p I haven't pushed out the new version, as I'm still poking it and prodding at it with sticks.  I'll push it out in just a couple minutes :)

**Comment by ccrama** [comment]
Oh ok, cool. I can test out the new version if needed ;)

**Comment by pirogoeth** [comment]
This may take a few minutes extra, as I have decided to go ahead and implement an interface to the HelpFactory.

**Comment by ccrama** [comment]
Alright, il come back in a bit. Thanks for the quick fixes :D

**Comment by pirogoeth** [comment]
No problem! I'm glad someone is finally showing interest in my bot!

**Comment by ccrama** [comment]
:)

**Comment by pirogoeth** [comment]
Try the very latest commit.

**Comment by ccrama** [comment]
It gives me an error when making the database, traceback no such file or directory

**Comment by ccrama** [comment]
but seems to be working now :)

**Comment by ccrama** [comment]
is there some sort of help command?

**Comment by ccrama** [comment]
Awesome :D

**Comment by pirogoeth** [comment]
I just re-committed, as there was some crazy ambiguity in the last commit that I totally did not intend.  Get the newest.  Now, you can either type '@help' in the channel, or you can use 'help' or '@help' in PM with the bot.

**Comment by ccrama** [comment]
Hmm @help doesnt show anything

**Comment by pirogoeth** [comment]
It doesn't send you anything in a notice?  What channel are you in on Mibbit?

**Comment by ccrama** [comment]
It's working great. Best bot ever! Thanks pirogoeth

**Comment by pirogoeth** [comment]
No problem! If you run in to any more problems file an issue, or if you want to request a plugin, send an email to pirogoeth@maio.me. Hope everything works out well!
